### PR TITLE
Make requested changes to create account form

### PR DESCRIPTION
**Pull request by jettdc**
Remove county from address
Add child placement agency or county certified with

### CODE REVIEW

**Review by TrevorW-code — APPROVED** [review]
Looks good!

**Review by TrevorW-code — APPROVED** [review]
Looks Good!

**Review by TrevorW-code — APPROVED** [review]
Looks good!

**Review by TrevorW-code — APPROVED** [review]
✓

**Review by taza6535 — APPROVED** [review]

**Pull request merged**
